# REF https://github.com/bitnami-labs/sealed-secrets/blob/main/helm/sealed-secrets/values.yaml
fullnameOverride: kubeseal
namespace: "kubeseal"
secretName: "sealed-secrets-key"
resources:
  limits:
    cpu: 200m
    memory: 164Mi
  requests:
    cpu: 100m
    memory: 128Mi
