# REF https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
namespaceOverride: cilium
kubeProxyReplacement: "true"
k8sServiceHost: 127.0.0.1
k8sServicePort: 6443
gatewayAPI:
  enabled: true
  enableAppProtocol: true
  enableAlpn: true
routingMode: tunnel
tunnelProtocol: vxlan
policyEnforcementMode: "never"
scheduling:
  mode: kube-scheduler
loadBalancer:
  l7:
    backend: envoy
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]
updateStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 0
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
operator:
  replicas: 1
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi
hubble:
  relay:
    enabled: true
    replicas: 1
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
envoy:
  enabled: true
  rollingUpdate:
    maxSurge: 25%
    maxUnavailable: 0
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 256Mi
ciliumEndpointSlice:
  enabled: true

authentication:
  mutual:
    spire:
      install:
        server:
          replicas: 1
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
