apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: openebs

helmCharts:
  - name: localpv-provisioner
    repo: https://openebs.github.io/dynamic-localpv-provisioner
    releaseName: openebs-lpv
    version: 4.4.0
    valuesFile: openebs-lpv-chart.values.yaml

patches:
  - target:
      kind: StorageClass
      name: hostpath
    patch: |-
      - op: add
        path: /allowVolumeExpansion
        value: true
