# REF: https://github.com/openebs/dynamic-localpv-provisioner/blob/v4.4.0/deploy/helm/charts/values.yaml

fullnameOverride: localpv-provisioner

localpv:
  replicas: 1
  basePath: "/var/localpv"
  updateStrategy:
    type: RollingUpdate
    maxSurge: 25%
    maxUnavailable: 0
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

hostpathClass:
  name: hostpath
  isDefaultClass: true
  xfsQuota:
    enabled: true
    softLimitGrace: "0%"
    hardLimitGrace: "0%"
  ext4Quota:
    enabled: true
    softLimitGrace: "0%"
    hardLimitGrace: "0%"
