apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cilium

resources:
  - ../base

patches:
  - path: patch-set-k8s-service-host.yaml
    target:
      kind: Deployment
      name: cilium-operator
      namespace: cilium
