# REF: https://github.com/openebs/dynamic-localpv-provisioner/blob/v4.4.0/deploy/helm/charts/values.yaml

fullnameOverride: openebs-lpv

localpv:
  updateStrategy:
    type: RollingUpdate
    maxSurge: 25%
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi
hostpathClass:
  name: hostpath
  isDefaultClass: true
